# Generated by Django 5.0.2 on 2024-03-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_user_todo_date_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
